modfileVersion: "v1"
id: github.com/SENERGY-Platform/mgw-ssh-dc/module
name: SSH Device-Connector
version: v0.0.1
type: device-connector
deploymentType: single
license: "Apache License 2.0"
dependencies:
  github.com/SENERGY-Platform/mgw-mqtt-broker:
    version: <v2.0.0
    requiredServices:
      broker:
        - refVar: MGW_MQTT_BROKER
          template: "{ref}:1883"
          services:
            - mgw-ssh-dc
services:
  mgw-ssh-dc:
    name: mgw-ssh-dc
    image: ghcr.io/senergy-platform/mgw-ssh-dc:v0.0.1
configs:
  discoveryIps:
    dataType: string
    isList: true
    targets:
      - refVar: HOSTS
        services:
          - mgw-ssh-dc
    userInput:
      type: text
      name: Hostnames/IPs
      description: "List of Hostnames or IPs, e.g. 192.168.0.1, 192.168.0.2"
  users:
    dataType: string
    targets:
      - refVar: USERS
        services:
          - mgw-ssh-dc
    userInput:
      type: text
      name: Usernames
      description: "List of usernames to use for login. Order has to match Hostnames/IPs"
  debug:
    dataType: string
    value: "false"
    options:
      - "false"
      - "true"
    targets:
      - refVar: DEBUG
        services:
          - mgw-ssh-dc
    userInput:
      type: text
      name: Debug
  deviceTypeId:
    dataType: string
    value: "urn:infai:ses:device-type:ada64e96-2f37-41d7-81b7-e695d0a39b78"
    targets:
      - refVar: DEVICE_TYPE_ID
        services:
          - mgw-ssh-dc
